# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Python, GitHub Actions, and Azure App Service: https://aka.ms/python-webapps-actions

name: Build and deploy Python app to Azure Web App - Desafio

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Instalacion de la version de python 
      - name: Preparando version de Python
      # Version de la "accion" que instalara Python 
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          # De la siguiente forma se instala "la mayor menor version". En este caso, la version 3.0
          # python-version: '3.x'
          # Arquitectura 'x64' o 'x86' (por defecto, este valor esta en 'x64')
          # arquitecture: 'x64'

      - name: Crear e iniciar el entorno virtual
        run: |
          python -m venv venv
          source venv/bin/activate
      
      - name: Instalar dependencias
        # Instala las dependencias especificadas en requirements.txt
        run: pip install -r requirements.txt
        # Tambien se puede instalar o actualizar las dependencias de esta forma
        # run: python -m pip install --upgrade pip

      - name: Utilizando Ruff
        run: |
          pip install ruff
          ruff check --output-format=github .

      - name: Instalar Tox
        run: pip install tox
        
      - name: Ejecutar tox
        run: tox -e py

      - name: Pruebas con pytest
        run: |
          pip install pytest
          # Ejecucion del archivo tests.py
          pytest tests/tests.py
        
      - name: Comprimir artefactos para el despliegue
        run: zip release.zip ./* -r
  
      - name: Subir artefatos para desplegar el trabajo
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: |
            release.zip
            !venv/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT

    steps:
      - name: Descargar artefactos 
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Descomprimir artefactos para el despliegue
        run: unzip release.zip

      
      - name: Loguear en Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_1044B5845F904569AAB6C8BADF8135F8 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_4282F4893EC449D0A6B7008E71B87D61 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_7E203C6E7D224DA288E2E65B47AFF238 }}

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          # Nombre de la aplicación
          app-name: 'Desafio'
          # Nombre del slot
          slot-name: 'Production'
          